import React from "react";

const GlobalContext = React.createContext({
  monthIndex: 0,
  setMonthIndex: (index) => {},
  smallCalendarMonth: 0,
  setSmallCalendarMonth: (index) => {},
  daySelected: null,
  setDaySelected: (day) => {},
  onShowModal: false,
  setOnShowModal: (bool) => {},
  showDayView: false,
  setShowDayView: (bool) => {},
  isClicked: false,
  setIsClicked: () => {},
  savedCalendarEvents: [],
  dispatchCallCalendarEvent: ({type, payload}) => {},
  savedDumperTODOS: [],
  dispatchCallDumperTODO: ({type, payload}) => {},
  savedTicklerFileEvents: [],
  dispatchCallTicklerFileEvent: ({type, payload}) => {},
  savedActionableTODOS: [],
  dispatchCallActionableTODO: ({type, payload}) => {},
  selectedCalendarEvent: null,
  setSelectedCalendarEvent: () => {},
  selectedTicklerFileEvent: null,
  setSelectedTicklerFileEvent: () => {},
  selectedDumperTODO: null,
  setSelectedDumperTODO: () => {},
  selectedActionableTODO: null, 
  setSelectedActionableTODO: () => {},
  calendarLabels: [],
  setCalendarLabels: ()=>{},
  updateCalendarLabel: () =>{},
  filteredCalendarEvents: [],
  ticklerFileLabels: [],
  setTicklerFileLabels: ()=>{},
  updateTicklerFileLabel: () =>{},
  onShowModal: false,
  setOnShowModal: () =>{},
  showMenu: false,
  setShowMenu: () =>{},
  resetAll: ()=>{}
});

export default GlobalContext;
